server:
  port: 8089

spring:
  application:
    name: authentication
  datasource:
    username: aiza
    url: jdbc:postgresql://localhost:5432/authentication
    password: password
jpa:
  hibernate:
    ddl-auto: create-drop
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
  show-sql: true